version: '3.9'
    
services:
  nginx:
    container_name: project-d-nginx
    image: nginx
    networks:
      - project-d-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
  qcard-frontend:
    container_name: project-d-qcard-frontend
    build:
      context: ./qcard_frontend/
      dockerfile: Dockerfile
    working_dir: /frontend
    volumes:
      - ./qcard_frontend/public:/frontend/public
      - ./qcard_frontend/src:/frontend/src
    entrypoint: npm start
    networks:
      - project-d-network
    restart: always

networks:
  project-d-network: