// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: pkg/xlimit/xlimit.proto

package xlimit

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type XLimitCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 在此架構下，各個microservice可以自訂他們的identity類別，
	// 例如某些microservice可以僅提供ip為identity，某些microservice則提供ip跟user-agent的混合。
	// 在這樣的情況下，也可以讓某些microservice去共用同種格式去做判別
	// 例如 service_a 跟 service_b 共同使用ip作為identity的判別，
	// 則 service_a 跟 service_b 就會有累加的作用
	// 我認為這樣可以帶給系統較大的擴充彈性，如果是僅用某種語言寫在某個package內的middleware，
	// 可能每換一種語言就會需要再重新寫一個，我認為這樣在維護上，會需要投入比較多的心力。
	// 再者，如果是以一個像這樣的封閉包裝並僅開放某些端口的形式進行，就可以有一個比較統一的格式，
	// 在多個microservice的架構中，或許能夠減少比較多的溝通協調時間。
	Identity       string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IncreaseNumber uint64 `protobuf:"varint,2,opt,name=increase_number,json=increaseNumber,proto3" json:"increase_number,omitempty"`
}

func (x *XLimitCheckRequest) Reset() {
	*x = XLimitCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_xlimit_xlimit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XLimitCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XLimitCheckRequest) ProtoMessage() {}

func (x *XLimitCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_xlimit_xlimit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XLimitCheckRequest.ProtoReflect.Descriptor instead.
func (*XLimitCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_xlimit_xlimit_proto_rawDescGZIP(), []int{0}
}

func (x *XLimitCheckRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *XLimitCheckRequest) GetIncreaseNumber() uint64 {
	if x != nil {
		return x.IncreaseNumber
	}
	return 0
}

type XLimitResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *XLimitResetRequest) Reset() {
	*x = XLimitResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_xlimit_xlimit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XLimitResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XLimitResetRequest) ProtoMessage() {}

func (x *XLimitResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_xlimit_xlimit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XLimitResetRequest.ProtoReflect.Descriptor instead.
func (*XLimitResetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_xlimit_xlimit_proto_rawDescGZIP(), []int{1}
}

func (x *XLimitResetRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type XLimitCheckReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity       string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	CountRemaining uint64 `protobuf:"varint,2,opt,name=count_remaining,json=countRemaining,proto3" json:"count_remaining,omitempty"`
	Timeleft       uint64 `protobuf:"varint,3,opt,name=timeleft,proto3" json:"timeleft,omitempty"`
	IsAllowed      bool   `protobuf:"varint,4,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
}

func (x *XLimitCheckReply) Reset() {
	*x = XLimitCheckReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_xlimit_xlimit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XLimitCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XLimitCheckReply) ProtoMessage() {}

func (x *XLimitCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_xlimit_xlimit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XLimitCheckReply.ProtoReflect.Descriptor instead.
func (*XLimitCheckReply) Descriptor() ([]byte, []int) {
	return file_pkg_xlimit_xlimit_proto_rawDescGZIP(), []int{2}
}

func (x *XLimitCheckReply) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *XLimitCheckReply) GetCountRemaining() uint64 {
	if x != nil {
		return x.CountRemaining
	}
	return 0
}

func (x *XLimitCheckReply) GetTimeleft() uint64 {
	if x != nil {
		return x.Timeleft
	}
	return 0
}

func (x *XLimitCheckReply) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

type XLimitGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // if identity == "*" -> Get all keys.
	KeysOnly bool   `protobuf:"varint,2,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
}

func (x *XLimitGetRequest) Reset() {
	*x = XLimitGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_xlimit_xlimit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XLimitGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XLimitGetRequest) ProtoMessage() {}

func (x *XLimitGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_xlimit_xlimit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XLimitGetRequest.ProtoReflect.Descriptor instead.
func (*XLimitGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_xlimit_xlimit_proto_rawDescGZIP(), []int{3}
}

func (x *XLimitGetRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *XLimitGetRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

type XLimitGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*XLimitCheckReply `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *XLimitGetReply) Reset() {
	*x = XLimitGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_xlimit_xlimit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XLimitGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XLimitGetReply) ProtoMessage() {}

func (x *XLimitGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_xlimit_xlimit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XLimitGetReply.ProtoReflect.Descriptor instead.
func (*XLimitGetReply) Descriptor() ([]byte, []int) {
	return file_pkg_xlimit_xlimit_proto_rawDescGZIP(), []int{4}
}

func (x *XLimitGetReply) GetResults() []*XLimitCheckReply {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_pkg_xlimit_xlimit_proto protoreflect.FileDescriptor

var file_pkg_xlimit_xlimit_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x78, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2f, 0x78, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x12, 0x58, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x12, 0x58, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x58, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22, 0x4b, 0x0a, 0x10, 0x58,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6b,
	0x65, 0x79, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x3d, 0x0a, 0x0e, 0x58, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x58, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0xa6, 0x01, 0x0a, 0x06, 0x58, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x3c, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6e, 0x64, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x12, 0x13, 0x2e, 0x58, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x58, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x2b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x58, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x58, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x58, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x58, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x75, 0x63, 0x6b, 0x74, 0x77, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x72, 0x65, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x64, 0x2f, 0x71, 0x69, 0x6e, 0x2d, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x78, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_xlimit_xlimit_proto_rawDescOnce sync.Once
	file_pkg_xlimit_xlimit_proto_rawDescData = file_pkg_xlimit_xlimit_proto_rawDesc
)

func file_pkg_xlimit_xlimit_proto_rawDescGZIP() []byte {
	file_pkg_xlimit_xlimit_proto_rawDescOnce.Do(func() {
		file_pkg_xlimit_xlimit_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_xlimit_xlimit_proto_rawDescData)
	})
	return file_pkg_xlimit_xlimit_proto_rawDescData
}

var file_pkg_xlimit_xlimit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_xlimit_xlimit_proto_goTypes = []interface{}{
	(*XLimitCheckRequest)(nil), // 0: XLimitCheckRequest
	(*XLimitResetRequest)(nil), // 1: XLimitResetRequest
	(*XLimitCheckReply)(nil),   // 2: XLimitCheckReply
	(*XLimitGetRequest)(nil),   // 3: XLimitGetRequest
	(*XLimitGetReply)(nil),     // 4: XLimitGetReply
}
var file_pkg_xlimit_xlimit_proto_depIdxs = []int32{
	2, // 0: XLimitGetReply.results:type_name -> XLimitCheckReply
	0, // 1: XLimit.CheckAndIncrease:input_type -> XLimitCheckRequest
	3, // 2: XLimit.Get:input_type -> XLimitGetRequest
	1, // 3: XLimit.Reset:input_type -> XLimitResetRequest
	2, // 4: XLimit.CheckAndIncrease:output_type -> XLimitCheckReply
	4, // 5: XLimit.Get:output_type -> XLimitGetReply
	2, // 6: XLimit.Reset:output_type -> XLimitCheckReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_xlimit_xlimit_proto_init() }
func file_pkg_xlimit_xlimit_proto_init() {
	if File_pkg_xlimit_xlimit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_xlimit_xlimit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XLimitCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_xlimit_xlimit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XLimitResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_xlimit_xlimit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XLimitCheckReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_xlimit_xlimit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XLimitGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_xlimit_xlimit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XLimitGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_xlimit_xlimit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_xlimit_xlimit_proto_goTypes,
		DependencyIndexes: file_pkg_xlimit_xlimit_proto_depIdxs,
		MessageInfos:      file_pkg_xlimit_xlimit_proto_msgTypes,
	}.Build()
	File_pkg_xlimit_xlimit_proto = out.File
	file_pkg_xlimit_xlimit_proto_rawDesc = nil
	file_pkg_xlimit_xlimit_proto_goTypes = nil
	file_pkg_xlimit_xlimit_proto_depIdxs = nil
}
