version:  "3.9"

services:
  xlimit-redis:
    image: "redis:alpine"
    container_name: project-d-xlimit-redis
    restart: always
    ports:
      - "6379"
  xlimit-grpc:
    container_name: project-d-xlimit-grpc
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /server
    volumes:
      - ./cmd:/server/cmd
      - ./internal:/server/internal
      - ./pkg:/server/pkg
    ports:
      - "50031:50031"
    entrypoint: go run /server/cmd/server/main.go
    restart: always
    depends_on:
      - xlimit-redis
    environment:
      REDIS_ADDR: "project-d-xlimit-redis:6379"
      REDIS_PASSWORD: ""
      REDIS_LAYER_PREFIX: "xlimit"
      REDIS_LAYER_LIMITNUM: 1000
      XLIMIT_GRPC_ADDR: ":50031"