# Generated by Django 3.1.1 on 2021-04-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=60, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%D/')),
                ('birthday', models.DateTimeField(verbose_name='club')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='interest')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='interest')),
                ('club', models.CharField(blank=True, max_length=255, null=True, verbose_name='club')),
                ('favorite_course', models.TextField(blank=True, null=True, verbose_name='favorite_course')),
                ('favorite_country', models.TextField(blank=True, null=True, verbose_name='favorite_country')),
                ('trouble', models.TextField(blank=True, null=True, verbose_name='trouble')),
                ('exchange', models.TextField(blank=True, null=True, verbose_name='exchange')),
                ('trying', models.TextField(blank=True, null=True, verbose_name='trying')),
                ('friends', models.ManyToManyField(blank=True, db_table='user_friends', to='qcard.User')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
