# Generated by Django 3.1.1 on 2021-04-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cate_photo/%Y/%m/%D/')),
                ('rule', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pair', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friends',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.category')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='gender')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%D/')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='club')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='interest')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='interest')),
                ('club', models.CharField(blank=True, max_length=255, null=True, verbose_name='club')),
                ('favorite_course', models.TextField(blank=True, null=True, verbose_name='favorite_course')),
                ('favorite_country', models.TextField(blank=True, null=True, verbose_name='favorite_country')),
                ('trouble', models.TextField(blank=True, null=True, verbose_name='trouble')),
                ('exchange', models.TextField(blank=True, null=True, verbose_name='exchange')),
                ('trying', models.TextField(blank=True, null=True, verbose_name='trying')),
                ('friends', models.ManyToManyField(blank=True, db_table='user_friends', related_name='friend', to='qcard.Friend')),
                ('pairing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing', to='qcard.friend')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.user')),
                ('current_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.post')),
                ('like', models.ManyToManyField(blank=True, db_table='reply_likes', related_name='like_reply', to='qcard.User')),
            ],
            options={
                'db_table': 'replys',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, db_table='post_likes', related_name='like_post', to='qcard.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='qcard.user'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='qcard.user'),
        ),
    ]
