# Generated by Django 3.1.1 on 2021-04-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user1',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user2',
            new_name='user_two',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
