# Generated by Django 3.1.1 on 2021-04-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcard', '0002_auto_20210405_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_friends', related_name='friend', to='qcard.Friend'),
        ),
    ]
