# Generated by Django 3.1.1 on 2021-04-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qcard', '0002_auto_20210404_0842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friend',
            table='friends',
        ),
    ]
