# Generated by Django 3.1.1 on 2021-04-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcard', '0003_auto_20210404_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pairing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing', to='qcard.friend'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_friends', related_name='friend', to='qcard.Friend'),
        ),
    ]
