# Generated by Django 3.1.1 on 2021-04-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcard', '0006_auto_20210404_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='cate_photo/%Y/%m/%D/')),
                ('rule', models.TextField()),
            ],
            options={
                'db_table': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.user')),
                ('like', models.ManyToManyField(blank=True, db_table='post_likes', related_name='like_post', to='qcard.User')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.user')),
                ('current_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcard.post')),
                ('like', models.ManyToManyField(blank=True, db_table='reply_likes', related_name='like_reply', to='qcard.User')),
            ],
            options={
                'db_table': 'replys',
            },
        ),
    ]
